apiVersion: v1
kind: Service
metadata:
  name: kodenames-service
spec:
  type: LoadBalancer
  selector:
    app: kodenames
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30035
